version: "3.7"
services:
  rspec:
    image: quay.io/forem/forem:testing
    container_name: forem_rails
    user: forem
    # ports:
    #   - "3000:3000"
    depends_on:
      - bundle
      - db
      - redis
      - yarn
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://forem:forem@db:5432/Forem_test
      DATABASE_URL_TEST: postgresql://forem:forem@db:5432/Forem_test
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_RPUSH_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      RACK_TIMEOUT_WAIT_TIMEOUT: 10000
      RACK_TIMEOUT_SERVICE_TIMEOUT: 10000
      STATEMENT_TIMEOUT: 10000
      APP_DOMAIN: rails
    volumes:
      - .:/opt/apps/forem:delegated
    entrypoint: ["dockerize", "-wait", "tcp://db:5432", "-wait", "tcp://redis:6379", "-wait", "file:///opt/apps/forem/vendor/bundle/.bundle_finished", "-timeout", "2700s", "-wait-retry-interval", "10s"]
    command: [ "bash", "-c", "./scripts/entrypoint.sh bootstrap && bundle exec rspec --format=progress"]

  bundle:
    image: quay.io/forem/forem:testing
    container_name: forem_bundle
    user: forem
    environment:
      RAILS_ENV: test
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/Forem_test
      DATABASE_URL_TEST: postgresql://forem:forem@db:5432/Forem_test
    volumes:
      - .:/opt/apps/forem:delegated
    command: ["./scripts/bundle.sh"]

  yarn:
    image: quay.io/forem/forem:testing
    container_name: forem_yarn
    user: forem
    environment:
      RAILS_ENV: test
      REDIS_SESSIONS_URL: redis://redis:6379
      REDIS_SIDEKIQ_URL: redis://redis:6379
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://forem:forem@db:5432/Forem_test
      DATABASE_URL_TEST: postgresql://forem:forem@db:5432/Forem_test
    volumes:
      - .:/opt/apps/forem:delegated
    command: yarn install --dev


  db:
    image: postgres:11-alpine
    container_name: forem_postgresql
    environment:
      POSTGRES_USER: forem
      POSTGRES_PASSWORD: forem
      POSTGRES_DB: Forem_test
    expose:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data:delegated

  redis:
    image: redis:6.0.9-alpine
    container_name: forem_redis
    expose:
      - "6379"

volumes:
  db_data:
